2023-11-16 17:44:02,106 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 17:44:12,818 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 57, in open
    connection.open()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\ios\ios.py", line 172, in open
    self.device = self._netmiko_open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\base.py", line 129, in _netmiko_open
    self._netmiko_device.enable()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\cisco_base_connection.py", line 26, in enable
    return super().enable(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 2008, in enable
    output += self.read_until_prompt()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 812, in read_until_prompt
    return self.read_until_pattern(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 721, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'R1' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2023-11-16 17:44:12,835 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 57, in open
    connection.open()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\ios\ios.py", line 172, in open
    self.device = self._netmiko_open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\base.py", line 129, in _netmiko_open
    self._netmiko_device.enable()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\cisco_base_connection.py", line 26, in enable
    return super().enable(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 2008, in enable
    output += self.read_until_prompt()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 812, in read_until_prompt
    return self.read_until_pattern(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 721, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'R2' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2023-11-16 17:45:27,288 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 17:45:27,316 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "linux". Is the library installed?

2023-11-16 17:45:27,317 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "linux". Is the library installed?

2023-11-16 17:48:50,151 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 17:48:50,197 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "ssh". Is the library installed?

2023-11-16 17:48:50,199 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "ssh". Is the library installed?

2023-11-16 17:49:27,499 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 17:49:27,508 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "ios-cisco". Is the library installed?

2023-11-16 17:49:27,509 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "ssh". Is the library installed?

2023-11-16 17:55:30,850 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 17:55:30,894 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2023-11-16 17:55:30,895 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2023-11-16 18:12:42,976 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 18:12:43,010 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "bin". Is the library installed?

2023-11-16 18:12:43,011 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "bin". Is the library installed?

2023-11-16 18:14:46,022 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 18:14:46,064 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2023-11-16 18:14:46,064 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2023-11-16 18:15:04,928 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 18:15:04,937 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2023-11-16 18:15:04,937 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2023-11-16 18:16:11,069 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 18:16:11,081 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2023-11-16 18:16:11,082 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 70, in get_network_driver
    raise ModuleImportError("Please provide a valid driver name.")
napalm.base.exceptions.ModuleImportError: Please provide a valid driver name.

2023-11-16 18:16:25,954 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 18:16:25,963 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 70, in get_network_driver
    raise ModuleImportError("Please provide a valid driver name.")
napalm.base.exceptions.ModuleImportError: Please provide a valid driver name.

2023-11-16 18:16:25,963 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 70, in get_network_driver
    raise ModuleImportError("Please provide a valid driver name.")
napalm.base.exceptions.ModuleImportError: Please provide a valid driver name.

2023-11-16 18:16:52,664 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 18:17:03,429 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 57, in open
    connection.open()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\ios\ios.py", line 172, in open
    self.device = self._netmiko_open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\base.py", line 129, in _netmiko_open
    self._netmiko_device.enable()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\cisco_base_connection.py", line 26, in enable
    return super().enable(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 2008, in enable
    output += self.read_until_prompt()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 812, in read_until_prompt
    return self.read_until_pattern(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 721, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'R2' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2023-11-16 18:17:03,430 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 57, in open
    connection.open()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\ios\ios.py", line 172, in open
    self.device = self._netmiko_open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\base.py", line 129, in _netmiko_open
    self._netmiko_device.enable()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\cisco_base_connection.py", line 26, in enable
    return super().enable(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 2008, in enable
    output += self.read_until_prompt()
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 812, in read_until_prompt
    return self.read_until_pattern(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\netmiko\base_connection.py", line 721, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'R1' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2023-11-16 18:17:56,841 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show interfaces summary']} on 2 hosts
2023-11-16 18:17:56,852 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "img". Is the library installed?

2023-11-16 18:17:56,852 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\tasks\napalm_cli.py", line 19, in napalm_cli
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 494, in get_connection
    self.open_connection(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir\core\inventory.py", line 546, in open_connection
    conn_obj.open(
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\nornir_napalm\plugins\connections\__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
  File "d:\12.github\cisco_automate_cls\nornir_venv\lib\site-packages\napalm\base\__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "img". Is the library installed?

